[package]
name = "euler347"
version = "0.1.0"
authors = ["slofslb@qq.com <slofslb@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.2.4"
